spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testapi?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://cdb-5jxq3ux4.bj.tencentcdb.com:10030/zhihu?serverTimezone=UTC
#    username: root
#    password: fbz961110
#    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml # 映射文件的路径扫描
server:
  port: 9200
